### ISSUE TITLE
Replaced taktik backend with <backend>

### ISSUE THREAD

**Issue by ehealthplatformstandards** [ehealthplatformstandards/laboResultVisualizationWebApp#6]
Should be changed to our own backend https://DNS when known, for testing this can be replaced by http://localhost

**Comment by bdc-ehealth** [comment]
@jmp-ehealth, @ec-ehealth,

do not forget to replace &lt;backend&gt; by the dns of our own backend before creating the image of the webapp. If the SSL resolution is handled by the proxy, this should be a https address.
